server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
service:
     name: cloud-thrift-service
---
spring:
  profiles: cloud

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}
  instance:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}