server:
  port: 8082


eureka:
   client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/
   instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  application:
    name: cloud-oauth2-resource-server




security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8081/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: app50jia
      clientSecret: 50jia123456
      authorized-grant-types: authorization_code,refresh_token,password
    resource:
      userInfoUri: http://localhost:8081/user